{{- $global := .Values.global | default dict -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "magic-gateway.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "magic-gateway.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "magic-gateway.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "magic-gateway.selectorLabels" . | nindent 8 }}
      {{- with (.Values.podAnnotations | default $global.podAnnotations) }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- include "common.images.pullSecrets" (dict "global" $global) | nindent 6 }}
      restartPolicy: Always
      containers:
      - name: {{ .Chart.Name }}
        image: {{ include "common.images.app" . }}
        imagePullPolicy: {{ .Values.imagePullPolicy | default $global.imagePullPolicy | default "Always" | quote }}
        command:
        - /app/api-gateway
        ports:
        - name: http
          containerPort: {{ .Values.service.targetPort }}
          protocol: TCP
        {{- if .Values.extraEnvVars }}
        env:
        {{- include "common.tplvalues.render" (dict "value" .Values.extraEnvVars "context" .) | nindent 8 }}
        {{- end }}
        envFrom:
        - configMapRef:
            name: {{ include "magic-gateway.fullname" . }}
        - secretRef:
            name: {{ include "magic-gateway.fullname" . }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
