apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: release-manager-dev
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/part-of: release-manager
spec:
  selector:
    app.kubernetes.io/name: redis
  ports:
    - name: redis
      port: 6379
      targetPort: redis
