apiVersion: v2
appVersion: 0.0.7
description: Magic Gateway - API gateway for AI services
keywords:
- magic
- gateway
- api
maintainers:
- email: ops@example.com
  name: Ops Team
name: magic-gateway
type: application
version: 0.0.5
