{{- $global := .Values.global | default dict }}
{{- if and $global.imageRegistryAuth $global.imageRegistryAuth.enabled }}
{{- $auth := printf "%s:%s" $global.imageRegistryAuth.username $global.imageRegistryAuth.password | b64enc }}
{{- $dockerConfig := dict "auths" (dict $global.imageRegistry (dict "username" $global.imageRegistryAuth.username "password" $global.imageRegistryAuth.password "email" ($global.imageRegistryAuth.email | default "") "auth" $auth)) }}
apiVersion: v1
kind: Secret
metadata:
  name: image-pull-secret
  namespace: {{ include "common.names.namespace" . | quote }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ $dockerConfig | toJson | b64enc }}
{{- end }}

