apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: patch-config.yaml
    target:
      kind: ConfigMap
      name: release-manager-config

replicas:
  - name: release-manager
    count: 2
