package devfixture

import (
	"context"
	"fmt"
	"os"

	"connectrpc.com/connect"

	orchestratorv1 "github.com/ndzuki/release-manager/api/gen/orchestrator/v1"
)

// phaseEnrollment creates one pending enrollment token per dev cluster and
// writes it to a 0600 file (REQ-065: devseed injects the token via Secret
// into each customer cluster; the file is the local stand-in until the
// Secret wiring lands). Re-running is idempotent: an existing token file is
// left untouched, so a consumed token stays consumed and a live token is
// not regenerated.
func (r *runner) phaseEnrollment(ctx context.Context) error {
	for _, seed := range clusterSeeds {
		customerID := r.state.customers[seed.customerKey]
		tokenPath := r.enrollmentTokenPath(seed.id)
		if _, err := os.Stat(tokenPath); err == nil {
			r.cfg.log().Info("enrollment token already seeded", "cluster", seed.id, "path", tokenPath)
			continue
		}
		req := connect.NewRequest(&orchestratorv1.CreateEnrollmentTokenRequest{
			CustomerId:   customerID,
			ClusterId:    seed.id,
			OperatorName: seed.id,
		})
		withAuth(req, r.state.adminToken)
		req.Header().Set("Idempotency-Key", idempotencyKey("enrollment", seed.id))
		response, err := r.clients.orch.CreateEnrollmentToken(ctx, req)
		if err != nil {
			return fmt.Errorf("create enrollment token for cluster %s: %w", seed.id, err)
		}
		if err := writeFileAtomic(tokenPath, []byte(response.Msg.GetToken()+"\n")); err != nil {
			return fmt.Errorf("write enrollment token for cluster %s: %w", seed.id, err)
		}
		r.cfg.log().Info("enrollment token written", "cluster", seed.id, "path", tokenPath)
	}
	return nil
}

// checkCommittedEnrollment verifies every cluster token file exists and is
// non-empty (the server-side token may legitimately be consumed by the
// operator agent; the file is the canonical local artifact).
func (r *runner) checkCommittedEnrollment(_ context.Context) error {
	for _, seed := range clusterSeeds {
		tokenPath := r.enrollmentTokenPath(seed.id)
		info, err := os.Stat(tokenPath)
		if err != nil {
			return fmt.Errorf("enrollment token file for cluster %s: %w", seed.id, err)
		}
		if info.Size() == 0 {
			return fmt.Errorf("enrollment token file for cluster %s is empty", seed.id)
		}
	}
	return nil
}

// resetLocalRuntimeState removes artifacts tied to the previous database
// generation before a reset re-seed (tokens were consumed by the old
// operator identities; the manifest is regenerated by verify).
func (r *runner) resetLocalRuntimeState() error {
	if err := os.RemoveAll(r.cfg.DataDir + "/" + enrollmentTokenDir); err != nil {
		return fmt.Errorf("clear enrollment tokens: %w", err)
	}
	if err := os.Remove(r.manifestPath()); err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("clear fixture manifest: %w", err)
	}
	return nil
}
