package devfixture

import (
	"crypto/ed25519"
	"crypto/rand"
	"crypto/x509"
	"encoding/base64"
	"encoding/pem"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// File layout of the seed's local artifacts (REQ-065).
const (
	progressFileName     = "dev-seed-progress.json"
	manifestFileName     = "dev-fixture.json"
	credentialsFileName  = "dev-credentials.env"
	trustRootDirName     = "dev-trust-root"
	trustRootKeyFileName = "dev-trust-root.key"
	enrollmentTokenDir   = "dev-enrollment-tokens"
)

// writeFileAtomic writes content to path via a temp file in the same
// directory followed by rename, so a crash never leaves a partially written
// progress/manifest/credentials file behind.
func writeFileAtomic(path string, content []byte, perm os.FileMode) error {
	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0o700); err != nil {
		return fmt.Errorf("create parent dir for %s: %w", path, err)
	}
	tmp, err := os.CreateTemp(dir, ".devfixture-*")
	if err != nil {
		return fmt.Errorf("create temp file for %s: %w", path, err)
	}
	tmpName := tmp.Name()
	defer func() { _ = os.Remove(tmpName) }() //nolint:errcheck // best-effort cleanup after rename or failure
	if err := tmp.Chmod(perm); err != nil {
		_ = tmp.Close()
		return fmt.Errorf("chmod temp file for %s: %w", path, err)
	}
	if _, err := tmp.Write(content); err != nil {
		_ = tmp.Close()
		return fmt.Errorf("write temp file for %s: %w", path, err)
	}
	if err := tmp.Sync(); err != nil {
		_ = tmp.Close()
		return fmt.Errorf("sync temp file for %s: %w", path, err)
	}
	if err := tmp.Close(); err != nil {
		return fmt.Errorf("close temp file for %s: %w", path, err)
	}
	if err := os.Rename(tmpName, path); err != nil {
		return fmt.Errorf("rename temp file to %s: %w", path, err)
	}
	return nil
}

// credentials holds the three seeded account passwords (REQ-065).
type credentials struct {
	admin    string
	deployer string
	reader   string
}

const passwordLength = 32

// credentialsEnv renders the dev-credentials.env document.
func (c credentials) envFile() []byte {
	return []byte(fmt.Sprintf(`# Generated by dev-seed — DO NOT COMMIT
DEV_ADMIN_PASSWORD=%s
DEV_DEPLOYER_PASSWORD=%s
DEV_READER_PASSWORD=%s
`, c.admin, c.deployer, c.reader))
}

// generatePasswords returns three fresh random passwords using only
// alphanumeric characters (safe to embed unquoted in a shell env file).
func generatePasswords() credentials {
	return credentials{
		admin:    randomPassword(),
		deployer: randomPassword(),
		reader:   randomPassword(),
	}
}

func randomPassword() string {
	const alphabet = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
	buffer := make([]byte, passwordLength)
	if _, err := rand.Read(buffer); err != nil {
		// crypto/rand failures are unrecoverable for secret generation.
		panic(fmt.Sprintf("devfixture: crypto/rand failure: %v", err)) //nolint:forbidigo // fail fast, no error path here
	}
	for i := range buffer {
		buffer[i] = alphabet[int(buffer[i])%len(alphabet)]
	}
	return string(buffer)
}

// loadCredentialsFile parses a valid dev-credentials.env: exactly the three
// KEY=VALUE lines with 32-character values. A malformed file yields
// (zero, false) so the caller regenerates (REQ-065 reuse semantics).
func loadCredentialsFile(path string) (credentials, bool) {
	raw, err := os.ReadFile(path)
	if err != nil {
		return credentials{}, false
	}
	result := credentials{}
	seen := 0
	for _, line := range strings.Split(string(raw), "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		key, value, ok := strings.Cut(line, "=")
		if !ok || len(value) != passwordLength {
			return credentials{}, false
		}
		switch strings.TrimSpace(key) {
		case "DEV_ADMIN_PASSWORD":
			result.admin = value
		case "DEV_DEPLOYER_PASSWORD":
			result.deployer = value
		case "DEV_READER_PASSWORD":
			result.reader = value
		default:
			return credentials{}, false
		}
		seen++
	}
	if seen != 3 || result.admin == "" || result.deployer == "" || result.reader == "" {
		return credentials{}, false
	}
	return result, true
}

// resolveCredentials applies the reuse-or-generate contract:
//
//   - explicit Config overrides win,
//   - an existing valid credentials file is reused,
//   - otherwise fresh passwords are generated and the file is written
//     (local mode; CI mode never writes and requires explicit values).
//
// When any effective password differs from the file content the file is
// rewritten so it stays the source of truth for later runs.
func (r *runner) resolveCredentials(cfg Config) (credentials, error) {
	path := filepath.Join(cfg.DataDir, credentialsFileName)
	fileCreds, fileOK := loadCredentialsFile(path)

	useCI := cfg.Mode == ModeCI
	if useCI {
		missing := []string{}
		if cfg.AdminPassword == "" {
			missing = append(missing, "DEV_ADMIN_PASSWORD")
		}
		if cfg.DeployerPassword == "" {
			missing = append(missing, "DEV_DEPLOYER_PASSWORD")
		}
		if cfg.ReaderPassword == "" {
			missing = append(missing, "DEV_READER_PASSWORD")
		}
		if len(missing) > 0 {
			return credentials{}, fmt.Errorf("ci profile requires env-injected passwords: %s", strings.Join(missing, ", "))
		}
		return credentials{admin: cfg.AdminPassword, deployer: cfg.DeployerPassword, reader: cfg.ReaderPassword}, nil
	}

	effective := fileCreds
	if fileOK && cfg.AdminPassword != "" {
		effective.admin = cfg.AdminPassword
	}
	if fileOK && cfg.DeployerPassword != "" {
		effective.deployer = cfg.DeployerPassword
	}
	if fileOK && cfg.ReaderPassword != "" {
		effective.reader = cfg.ReaderPassword
	}
	if !fileOK {
		effective = generatePasswords()
		if cfg.AdminPassword != "" {
			effective.admin = cfg.AdminPassword
		}
		if cfg.DeployerPassword != "" {
			effective.deployer = cfg.DeployerPassword
		}
		if cfg.ReaderPassword != "" {
			effective.reader = cfg.ReaderPassword
		}
	}
	// Rewrite when the file is absent, malformed, or stale relative to
	// explicit overrides so the file always mirrors the effective set.
	needsWrite := !fileOK || effective != fileCreds
	if needsWrite {
		if err := writeFileAtomic(path, effective.envFile(), 0o600); err != nil {
			return credentials{}, fmt.Errorf("write credentials file: %w", err)
		}
	}
	return effective, nil
}

// trustRootKeyPath returns the on-disk Dev Trust Root private key location.
func (r *runner) trustRootKeyPath() string {
	return filepath.Join(r.cfg.DataDir, trustRootDirName, trustRootKeyFileName)
}

// loadOrGenerateTrustRootKey loads the persisted dev trust root private key
// (local mode, 0600) or the CI-injected key, generating a fresh Ed25519 key
// when neither exists (REQ-065 trust stage).
func (r *runner) loadOrGenerateTrustRootKey(cfg Config) (ed25519.PrivateKey, error) {
	if cfg.Mode == ModeCI {
		if cfg.TrustRootPrivateKey == "" {
			return nil, fmt.Errorf("ci profile requires DEV_TRUST_ROOT_PRIVATE_KEY")
		}
		return decodePrivateKey([]byte(cfg.TrustRootPrivateKey))
	}
	path := r.trustRootKeyPath()
	raw, err := os.ReadFile(path)
	if err == nil {
		key, decodeErr := decodePrivateKey(raw)
		if decodeErr != nil {
			return nil, fmt.Errorf("load dev trust root key: %w", decodeErr)
		}
		return key, nil
	}
	if !errors.Is(err, os.ErrNotExist) {
		return nil, fmt.Errorf("read dev trust root key: %w", err)
	}
	_, key, err := ed25519.GenerateKey(rand.Reader)
	if err != nil {
		return nil, fmt.Errorf("generate dev trust root key: %w", err)
	}
	encoded, err := encodePrivateKey(key)
	if err != nil {
		return nil, err
	}
	if err := writeFileAtomic(path, encoded, 0o600); err != nil {
		return nil, fmt.Errorf("write dev trust root key: %w", err)
	}
	r.cfg.log().Info("dev trust root key generated", "path", path)
	return key, nil
}

func encodePrivateKey(key ed25519.PrivateKey) ([]byte, error) {
	der, err := x509.MarshalPKCS8PrivateKey(key)
	if err != nil {
		return nil, fmt.Errorf("marshal dev trust root key: %w", err)
	}
	return pem.EncodeToMemory(&pem.Block{Type: "PRIVATE KEY", Bytes: der}), nil
}

// decodePrivateKey accepts a PKCS8 PEM block or a raw base64 encoding of one
// (convenience for CI secret injection).
func decodePrivateKey(raw []byte) (ed25519.PrivateKey, error) {
	block, _ := pem.Decode(raw)
	if block == nil {
		decoded, err := base64.StdEncoding.DecodeString(strings.TrimSpace(string(raw)))
		if err != nil {
			return nil, fmt.Errorf("dev trust root key must be PEM or base64 PEM")
		}
		block, _ = pem.Decode(decoded)
	}
	if block == nil {
		return nil, fmt.Errorf("dev trust root key must be PEM or base64 PEM")
	}
	key, err := x509.ParsePKCS8PrivateKey(block.Bytes)
	if err != nil {
		return nil, fmt.Errorf("parse dev trust root key: %w", err)
	}
	edKey, ok := key.(ed25519.PrivateKey)
	if !ok {
		return nil, fmt.Errorf("dev trust root key must be Ed25519")
	}
	return edKey, nil
}

// enrollmentTokenPath returns the token file path for one cluster.
func (r *runner) enrollmentTokenPath(clusterID string) string {
	return filepath.Join(r.cfg.DataDir, enrollmentTokenDir, clusterID+".token")
}
