package devfixture

import (
	"crypto/ed25519"
	"crypto/rand"
	"crypto/x509"
	"encoding/base64"
	"encoding/pem"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// File layout of the seed's local artifacts (REQ-065).
const (
	progressFileName     = "dev-seed-progress.json"
	manifestFileName     = "dev-fixture.json"
	credentialsFileName  = "dev-credentials.env"
	trustRootDirName     = "dev-trust-root"
	trustRootKeyFileName = "dev-trust-root.key"
	archiveDirName       = "archive"
	//nolint:gosec // directory name, not a credential (G101 false positive on "token")
	enrollmentTokenDir = "dev-enrollment-tokens"
)

// writeFileAtomic writes content to path via a temp file in the same
// directory followed by rename, so a crash never leaves a partially written
// progress/manifest/credentials file behind. The file is always created with
// mode 0600: every artifact this module writes is a credential, key or
// environment record (REQ-065 security boundary).
func writeFileAtomic(path string, content []byte) error {
	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0o700); err != nil {
		return fmt.Errorf("create parent dir for %s: %w", path, err)
	}
	tmp, err := os.CreateTemp(dir, ".devfixture-*")
	if err != nil {
		return fmt.Errorf("create temp file for %s: %w", path, err)
	}
	tmpName := tmp.Name()
	if err := tmp.Chmod(0o600); err != nil {
		_ = tmp.Close()
		_ = os.Remove(tmpName)
		return fmt.Errorf("chmod temp file for %s: %w", path, err)
	}
	defer func() { _ = os.Remove(tmpName) }() //nolint:errcheck // best-effort cleanup after rename or failure
	if _, err := tmp.Write(content); err != nil {
		_ = tmp.Close()
		return fmt.Errorf("write temp file for %s: %w", path, err)
	}
	if err := tmp.Sync(); err != nil {
		_ = tmp.Close()
		return fmt.Errorf("sync temp file for %s: %w", path, err)
	}
	if err := tmp.Close(); err != nil {
		return fmt.Errorf("close temp file for %s: %w", path, err)
	}
	if err := os.Rename(tmpName, path); err != nil {
		return fmt.Errorf("rename temp file to %s: %w", path, err)
	}
	return nil
}

// credentials holds the four seeded account passwords (REQ-065; the
// e2e-runner account is REQ-066's E2E write identity, 批次4 D1/D3).
type credentials struct {
	admin    string
	deployer string
	reader   string
	runner   string
}

const passwordLength = 32

// credentialsEnv renders the dev-credentials.env document.
func (c credentials) envFile() []byte {
	return []byte(fmt.Sprintf(`# Generated by dev-seed — DO NOT COMMIT
DEV_ADMIN_PASSWORD=%s
DEV_DEPLOYER_PASSWORD=%s
DEV_READER_PASSWORD=%s
E2E_RUNNER_PASSWORD=%s
`, c.admin, c.deployer, c.reader, c.runner))
}

// generatePasswords returns four fresh random passwords using only
// alphanumeric characters (safe to embed unquoted in a shell env file).
func generatePasswords() credentials {
	return credentials{
		admin:    randomPassword(),
		deployer: randomPassword(),
		reader:   randomPassword(),
		runner:   randomPassword(),
	}
}

func randomPassword() string {
	const alphabet = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
	buffer := make([]byte, passwordLength)
	if _, err := rand.Read(buffer); err != nil {
		// crypto/rand failures are unrecoverable for secret generation.
		panic(fmt.Sprintf("devfixture: crypto/rand failure: %v", err)) //nolint:forbidigo // fail fast, no error path here
	}
	for i := range buffer {
		buffer[i] = alphabet[int(buffer[i])%len(alphabet)]
	}
	return string(buffer)
}

// credentialFields maps dev-credentials.env keys to the credentials fields
// (the four development accounts of REQ-065, AC-065-34).
func credentialFields(result *credentials) map[string]*string {
	return map[string]*string{
		"DEV_ADMIN_PASSWORD":    &result.admin,
		"DEV_DEPLOYER_PASSWORD": &result.deployer,
		"DEV_READER_PASSWORD":   &result.reader,
		"E2E_RUNNER_PASSWORD":   &result.runner,
	}
}

// loadCredentialsFile parses a valid dev-credentials.env: exactly the four
// KEY=VALUE lines with 32-character [A-Za-z0-9] values (REQ-065 D2). A
// malformed file yields (zero, false) so the caller regenerates (REQ-065
// reuse semantics).
func loadCredentialsFile(path string) (credentials, bool) {
	raw, err := os.ReadFile(path)
	if err != nil {
		return credentials{}, false
	}
	result := credentials{}
	fields := credentialFields(&result)
	seen := 0
	for _, line := range strings.Split(string(raw), "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		key, value, ok := strings.Cut(line, "=")
		field, known := fields[strings.TrimSpace(key)]
		if !ok || !known || !validPassword(value) {
			return credentials{}, false
		}
		*field = value
		seen++
	}
	if seen != len(fields) || result.admin == "" || result.deployer == "" || result.reader == "" || result.runner == "" {
		return credentials{}, false
	}
	return result, true
}

// validPassword enforces the D2 password contract: exactly 32 characters
// from [A-Za-z0-9] (≈190 bit, alphanumeric so the value is safe unquoted in
// a shell env file).
func validPassword(value string) bool {
	if len(value) != passwordLength {
		return false
	}
	for i := 0; i < len(value); i++ {
		c := value[i]
		if c < '0' || c > 'z' || (c > '9' && c < 'A') || (c > 'Z' && c < 'a') {
			return false
		}
	}
	return true
}

// resolveCredentials applies the reuse-or-generate contract:
//
//   - explicit Config overrides win,
//   - an existing valid credentials file is reused,
//   - otherwise fresh passwords are generated and the file is written
//     (local mode; CI mode never writes and requires explicit values).
//
// When any effective password differs from the file content the file is
// rewritten so it stays the source of truth for later runs.
func (r *runner) resolveCredentials(cfg Config) (credentials, error) {
	if cfg.Mode == ModeCI {
		return ciCredentials(cfg)
	}
	path := filepath.Join(cfg.DataDir, credentialsFileName)
	fileCreds, fileOK := loadCredentialsFile(path)

	effective := localCredentials(fileCreds, fileOK, cfg)
	// Rewrite when the file is absent, malformed, or stale relative to
	// explicit overrides so the file always mirrors the effective set.
	if !fileOK || effective != fileCreds {
		if err := writeFileAtomic(path, effective.envFile()); err != nil {
			return credentials{}, fmt.Errorf("write credentials file: %w", err)
		}
	}
	return effective, nil
}

// ciCredentials requires all four passwords to be env-injected and never
// touches the credentials file (REQ-065 CI profile).
func ciCredentials(cfg Config) (credentials, error) {
	missing := []string{}
	if cfg.AdminPassword == "" {
		missing = append(missing, "DEV_ADMIN_PASSWORD")
	}
	if cfg.DeployerPassword == "" {
		missing = append(missing, "DEV_DEPLOYER_PASSWORD")
	}
	if cfg.ReaderPassword == "" {
		missing = append(missing, "DEV_READER_PASSWORD")
	}
	if cfg.E2ERunnerPassword == "" {
		missing = append(missing, "E2E_RUNNER_PASSWORD")
	}
	if len(missing) > 0 {
		return credentials{}, fmt.Errorf("ci profile requires env-injected passwords: %s", strings.Join(missing, ", "))
	}
	// D2 contract applies to the ci profile too: every injected password
	// must be 32 chars of [A-Za-z0-9].
	for name, value := range map[string]string{
		"DEV_ADMIN_PASSWORD": cfg.AdminPassword, "DEV_DEPLOYER_PASSWORD": cfg.DeployerPassword, "DEV_READER_PASSWORD": cfg.ReaderPassword, "E2E_RUNNER_PASSWORD": cfg.E2ERunnerPassword,
	} {
		if !validPassword(value) {
			return credentials{}, fmt.Errorf("ci profile password %s must be 32 characters of [A-Za-z0-9]", name)
		}
	}
	return credentials{admin: cfg.AdminPassword, deployer: cfg.DeployerPassword, reader: cfg.ReaderPassword, runner: cfg.E2ERunnerPassword}, nil
}

// localCredentials merges explicit config overrides on top of the existing
// credentials file, generating fresh passwords only when no file exists.
func localCredentials(fileCreds credentials, fileOK bool, cfg Config) credentials {
	if !fileOK {
		fileCreds = generatePasswords()
	}
	if cfg.AdminPassword != "" {
		fileCreds.admin = cfg.AdminPassword
	}
	if cfg.DeployerPassword != "" {
		fileCreds.deployer = cfg.DeployerPassword
	}
	if cfg.ReaderPassword != "" {
		fileCreds.reader = cfg.ReaderPassword
	}
	if cfg.E2ERunnerPassword != "" {
		fileCreds.runner = cfg.E2ERunnerPassword
	}
	return fileCreds
}

// trustRootKeyPath returns the on-disk Dev Trust Root private key location.
func (r *runner) trustRootKeyPath() string {
	return filepath.Join(r.cfg.DataDir, trustRootDirName, trustRootKeyFileName)
}

// loadOrGenerateTrustRootKey loads the persisted dev trust root private key
// (local mode, 0600) or the CI-injected key, generating a fresh Ed25519 key
// when neither exists (REQ-065 trust stage).
func (r *runner) loadOrGenerateTrustRootKey(cfg Config) (ed25519.PrivateKey, error) {
	if cfg.Mode == ModeCI {
		if cfg.TrustRootPrivateKey == "" {
			return nil, fmt.Errorf("ci profile requires DEV_TRUST_ROOT_PRIVATE_KEY")
		}
		return decodePrivateKey([]byte(cfg.TrustRootPrivateKey))
	}
	path := r.trustRootKeyPath()
	raw, err := os.ReadFile(path)
	if err == nil {
		key, decodeErr := decodePrivateKey(raw)
		if decodeErr != nil {
			return nil, fmt.Errorf("load dev trust root key: %w", decodeErr)
		}
		return key, nil
	}
	if !errors.Is(err, os.ErrNotExist) {
		return nil, fmt.Errorf("read dev trust root key: %w", err)
	}
	_, key, err := ed25519.GenerateKey(rand.Reader)
	if err != nil {
		return nil, fmt.Errorf("generate dev trust root key: %w", err)
	}
	encoded, err := encodePrivateKey(key)
	if err != nil {
		return nil, err
	}
	if err := writeFileAtomic(path, encoded); err != nil {
		return nil, fmt.Errorf("write dev trust root key: %w", err)
	}
	r.cfg.log().Info("dev trust root key generated", "path", path)
	return key, nil
}

func encodePrivateKey(key ed25519.PrivateKey) ([]byte, error) {
	der, err := x509.MarshalPKCS8PrivateKey(key)
	if err != nil {
		return nil, fmt.Errorf("marshal dev trust root key: %w", err)
	}
	return pem.EncodeToMemory(&pem.Block{Type: "PRIVATE KEY", Bytes: der}), nil
}

// decodePrivateKey accepts a PKCS8 PEM block or a raw base64 encoding of one
// (convenience for CI secret injection).
func decodePrivateKey(raw []byte) (ed25519.PrivateKey, error) {
	block, _ := pem.Decode(raw)
	if block == nil {
		decoded, err := base64.StdEncoding.DecodeString(strings.TrimSpace(string(raw)))
		if err != nil {
			return nil, fmt.Errorf("dev trust root key must be PEM or base64 PEM")
		}
		block, _ = pem.Decode(decoded)
	}
	if block == nil {
		return nil, fmt.Errorf("dev trust root key must be PEM or base64 PEM")
	}
	key, err := x509.ParsePKCS8PrivateKey(block.Bytes)
	if err != nil {
		return nil, fmt.Errorf("parse dev trust root key: %w", err)
	}
	edKey, ok := key.(ed25519.PrivateKey)
	if !ok {
		return nil, fmt.Errorf("dev trust root key must be Ed25519")
	}
	return edKey, nil
}

// enrollmentTokenPath returns the token file path for one cluster.
func (r *runner) enrollmentTokenPath(clusterID string) string {
	return filepath.Join(r.cfg.DataDir, enrollmentTokenDir, clusterID+".token")
}

// archiveProgress writes the current progress document to
// data/archive/archive-<ISO8601>-<fixture_version>.json (AC-065-30) and
// prunes the archive to the most recent maxArchiveGenerations entries.
// No-op when there is no previous progress file or its fixture version is
// empty (first seed). dev-purge and dev-reset-data never delete data/archive.
func (r *runner) archiveProgress() error {
	if r.progress.FixtureVersion == "" {
		return nil
	}
	if _, err := os.Stat(r.progressPath()); errors.Is(err, os.ErrNotExist) {
		return nil
	}
	raw, err := os.ReadFile(r.progressPath())
	if err != nil {
		return fmt.Errorf("read progress for archive: %w", err)
	}
	archiveDir := filepath.Join(r.cfg.DataDir, archiveDirName)
	if err := os.MkdirAll(archiveDir, 0o700); err != nil {
		return fmt.Errorf("create archive dir: %w", err)
	}
	// ISO 8601 with hyphens instead of colons (filename-safe on every
	// filesystem); Z suffix keeps it UTC-parseable. The name is assembled
	// from the fixed archive scheme and the maintainer-controlled version
	// constant — never from caller input.
	name := fmt.Sprintf("archive-%s-%s.json", r.cfg.now().UTC().Format("2006-01-02T15-04-05Z"), r.progress.FixtureVersion)
	archivePath := filepath.Join(archiveDir, name)
	//nolint:gosec // G703: path built from the fixed archive scheme above, not caller input
	if err := os.WriteFile(archivePath, raw, 0o600); err != nil {
		return fmt.Errorf("write archive %s: %w", name, err)
	}
	r.cfg.log().Info("fixture progress archived", "archive", filepath.Join(archiveDirName, name), "version", r.progress.FixtureVersion)
	return r.pruneArchive(archiveDir)
}

// pruneArchive keeps only the maxArchiveGenerations most recent archives in
// the archive directory (AC-065-30). Only files matching the
// archive-<ISO8601>-<version>.json scheme are considered so foreign files
// are never touched.
func (r *runner) pruneArchive(archiveDir string) error {
	entries, err := os.ReadDir(archiveDir)
	if err != nil {
		return fmt.Errorf("read archive dir: %w", err)
	}
	var archives []string
	for _, entry := range entries {
		name := entry.Name()
		if !entry.IsDir() && strings.HasPrefix(name, "archive-") && strings.HasSuffix(name, ".json") {
			archives = append(archives, name)
		}
	}
	sort.Slice(archives, func(i, j int) bool {
		// Names share one timestamp format: lexicographic == chronological.
		return archives[i] > archives[j]
	})
	for _, old := range archives[maxArchiveGenerations:] {
		if err := os.Remove(filepath.Join(archiveDir, old)); err != nil {
			return fmt.Errorf("prune archive %s: %w", old, err)
		}
		r.cfg.log().Info("old fixture archive pruned", "archive", old)
	}
	return nil
}
