apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: operator-identity
  namespace: release-manager-customer
  labels:
    app.kubernetes.io/part-of: release-manager
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
