apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml

commonLabels:
  app.kubernetes.io/name: release-manager
  app.kubernetes.io/part-of: release-operator

images:
  - name: release-manager
    newName: harbor.example.com/release-operator/release-manager
    newTag: latest
