apiVersion: v1
kind: Service
metadata:
  name: release-manager
  labels:
    app.kubernetes.io/name: release-manager
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    targetPort: http
    protocol: TCP
  - name: grpc
    port: 8443
    targetPort: grpc
    protocol: TCP
  selector:
    app.kubernetes.io/name: release-manager
