{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "sandbox-gateway.serviceAccountName" . }}
  labels:
    {{- include "sandbox-gateway.labels" . | nindent 4 }}
    app: sandbox-components
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "sandbox-gateway.serviceAccountName" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "sandbox-gateway.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}

