{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "sandbox-gateway.serviceAccountName" . }}
  labels:
    {{- include "sandbox-gateway.labels" . | nindent 4 }}
    app: sandbox-components
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - list
  - get
- apiGroups:
  - ""
  resources:
  - persistentvolumes
  verbs:
  - list
  - get
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  - pods
  verbs:
  - list
  - get
  - create
  - update
  - patch
  - delete
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - update
  - patch
- apiGroups:
  - apps
  resources:
  - daemonsets
  verbs:
  - list
  - get
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - list
  - get
  - create
  - update
  - patch
  - delete
{{- end }}

