{{- $s3 := .Values.s3 | default dict }}
apiVersion: v1
kind: Secret
metadata:
  name: s3-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sandbox-gateway.labels" . | nindent 4 }}
type: Opaque
data:
  akId: {{ $s3.akId | default "" | b64enc }}
  akSecret: {{ $s3.akSecret | default "" | b64enc }}
