apiVersion: v1
kind: Service
metadata:
  name: {{ include "sandbox-gateway.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sandbox-gateway.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  sessionAffinity: None
  internalTrafficPolicy: Cluster
  ipFamilyPolicy: SingleStack
  ipFamilies:
  - IPv4
  ports:
  - name: http
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
    protocol: TCP
  selector:
    {{- include "sandbox-gateway.selectorLabels" . | nindent 4 }}

