apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: release-manager-postgres-data
  namespace: release-manager-dev
  labels:
    app.kubernetes.io/part-of: release-manager
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
