apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: release-manager-dev
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: release-manager
spec:
  selector:
    app.kubernetes.io/name: postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
