name: Sync to GitCode

on:
  push:
    branches:
      - main # 如果你默认的分支是 master，请修改为 master

env:
  GITCODE_USER: ndmizuki
jobs:
  gitcode-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 获取完整提交历史，防止强制推送失败

      - name: Push to GitCode
        run: |
          # 格式化 GitCode 的远程仓库地址，带上用户名和 Token 鉴权
          # 假设你的 GitCode 仓库路径为 gitcode.com/你的用户名/你的仓库名.git
          REMOTE_URL="https://${{ env.GITCODE_USER }}:${{ secrets.GITCODE_TOKEN }}@gitcode.com/${{ env.GITCODE_USER }}/${{ github.event.repository.name }}.git"

          # 强制将本地全部分支与标签推送到 GitCode
          git push --mirror "$REMOTE_URL"
